# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Set Settings.xml
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[{ "id": "central", "url": "https://repo1.maven.org/maven2", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },{ "id": "github", "url": "https://maven.pkg.github.com/bcollins92/artefacts"}]'
        servers: '[{ "id": "github", "username": "bcollins", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
        profiles: '[{ "id": "sonar", "activation":{ "activeByDefault" : "true" }, "properties": {"sonar.host.url" : "https://sonarcloud.io" }}]'
      
    - name: Run tests with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B clean verify

  sonar-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Set Settings.xml
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[{ "id": "central", "url": "https://repo1.maven.org/maven2", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },{ "id": "github", "url": "https://maven.pkg.github.com/bcollins92/artefacts"}]'
        servers: '[{ "id": "github", "username": "bcollins", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
        profiles: '[{ "id": "sonar", "activation":{ "activeByDefault" : "true" }, "properties": {"sonar.host.url" : "https://sonarcloud.io" }}]'
      
    - name: Run tests with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B clean install -DskipTests sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.coverage.jacoco.xmlReportPaths="./target/site/jacoco"

  publish-docker:
    runs-on: ubuntu-latest
   # needs: [integration-test, sonar-scan]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Set Settings.xml
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "central", "url": "https://repo1.maven.org/maven2", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },{ "id": "github", "url": "https://maven.pkg.github.com/bcollins92/artefacts"}]'
          servers: '[{ "id": "github", "username": "bcollins", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
          profiles: '[{ "id": "sonar", "activation":{ "activeByDefault" : "true" }, "properties": {"sonar.host.url" : "https://sonarcloud.io" }}]'
        
      - name: Build the project
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -U clean install -DskipTests
        
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: bcollins92/artefacts
          tags: ghcr.io/bcollins92/artefacts/user-service:latest
    
    
    
    
    
    
    
    
    
